# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19c9078ee203b08af366761ed286f4477b8916cb786f725cb7037ee804b7e2ebbbbd4bf5072cd2b498e6202414a4b12a1c19fe84541f43f20c5f547421c56729

test:
  secret_key_base: 5bf42e2ea76d0297d34ac8a1565166c8a930bd146e554f5a4bc334ed763f5b693e5c7d397114b2213422c71c6bf92a006779b704f8cf372ca4f381c3a3e55cbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
